version: 2.0
executorType: docker
containerInfo:
  - image: yarnpkg/dev:latest
stages:
  build:
    workDir: /home/ubuntu/project
    steps:
      - type: checkout

      - type: cache-restore
        key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - type: shell
        command: yarn install

      - type: shell
        name: Tests
        command: |
          node -v
          yarn test
      - type: cache-save
        key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
          - "~/.yarn-cache"

      - type: artifacts-store
        path: artifacts/
        destination: yarnpkg