version: 2
jobs:
  build:
    docker:
        - image: yarnpkg/dev:latest
    working_directory: ~/rian
    steps:
        - checkout
        - restore_cache:
            keys: 
              - rian-{{ .Branch }}-{{ checksum "yarn.lock" }}
              - rian-{{ .Branch }}
              - rian-master
        - run:
            name: Install Dependencies
            command: yarn install
        - run:
            name: Test
            command: |
              node -v
              yarn run test:ci
        - save_cache:
            key: rian-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
              - "~/.cache/yarn"
        - store_artifacts:
            path: /artifacts
            destination: prefix
        - store_test_results:
            path: /test-results
        - deploy:
            name: Deploy
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ./scripts/circleci/upload_build.sh
                aws s3 sync ~/rian s3://$bucket/ --delete
              fi