version: 2
jobs:
  build:
    docker: 
      - image: node:7.4.0
      - image: yarnpkg/dev:latest
    working_directory: /home/ubuntu/rian
    steps:
      - checkout
      - restore_cache:
          key: rian-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Tests
          command: npm test
      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "~/.yarn-cache"
      - store_artifacts:
          path: artifacts/