version: 2
jobs:
  build:
    working_directory: ~/rian
    docker:
        - image: governmentpaas/awscli:latest
        - image: yarnpkg/dev:latest
    steps:
        - checkout
        - restore_cache:
            keys: 
              - rian-{{ .Branch }}-{{ checksum "yarn.lock" }}
              - rian-{{ .Branch }}
              - rian-master
        - run:
            name: Install Dependencies
            command: yarn install
        - run:
            name: Test
            command: |
              node -v
              yarn run test:ci
        - save_cache:
            key: rian-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
              - "~/.cache/yarn"
        - store_artifacts:
            path: /artifacts
            destination: prefix
        - store_test_results:
            path: /test-results
        - deploy:
            command: |
              sh ~/rian/scripts/circleci/upload_build.sh